language: csharp
dotnet: 2.1.200
install:
script:
- "./build.sh"
env:
  global:
    secure: JTjsmLo5erQ7tz0ygiQQ0A5btFjgKfOtm9e/rNiEOCgJVa427xQsvZJX4TJtDMj04f11pJdYxLyIgFa4Mk+H+Q1TfbUPNIwi4Y8uVkEgQVnx9SZxhX+8Ns7tN7lRwyUQkucAxfuE1h2mJ1OopUL8leRF4RbLZlknKlHZyemCBclMUNOXmcAAsQpAp7YHlEo+V+7MeQY1t+IIXvfRBnXmq/WHWFJ25CsNfJw5Y6lFDERYf9skskEOd1jDnbw9rCRg8uvZu/T6znFp3e+sBaguYkn49r8CezEw+lNmw/u7+ISbEnSn81cE94fhKfhQFSZRZROsJMqOGRv9rIDsMRvKYYbOAwrLQUmgv9fQWB55i7Ob40aCA9N/YfxLD5QqzIwnzFS2OMP5VOryudXcWnekVaj/5UdqYXXMLehb0xV6vOBBUGWIDbnfOZtShBXcCfeUf/XwQpD963/KA72vOa+fcGBABI1Yw2OL8fadK2azR3jiPdsGD1fzHJnsKCqbk0P4PJCIfIlcyojLzmwpIx917ziSFTmT46S/e71xZQZjnYNfWFxkmgQ/hiwNlwvupQ5xw1jNX8nNJVncullR6wLzDw7cEyZOmo0GdXKF+upDm7sMPtV4iLisIW6F9OxVzNpvEn1iaUIciHwxRPOPPk9C6mr3k4alnvMzhGqX6XHGV1M=
